server:
  port: 9999
spring:
  application:
    name: security
  database:
    driverClassName: com.mysql.cj.jdbc.Driver
  datasource:
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3308/bench?useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true